# exec-once =
exec-once = awww-daemon
exec-once = awww-restore
# exec-once = swww img -t=none $(find /home/tai/wallpapers/cats -type f | shuf -n 1)
exec-once = otd-daemon
# exec-once = quickshell
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dunst
exec-once = vicinae server
exec-once = systemctl --user start hyprpolkitagent

# apps
exec-once = [workspace 1] pear-desktop
exec-once = [workspace 2] vesktop
exec-once = [workspace 4] dkwtct
exec-once = [workspace 5] zen-browser
exec-once = [workspace 7] prismlauncher
