input {
    kb_layout = personal
    kb_variant = colemak-sumniki
    kb_options = ctrl:nocaps,grp:caps_toggle
    follow_mouse = 1

    sensitivity = -0.89 # -1.0 - 1.0, 0 means no modification.
    # sensitivity = -0.90 # -1.0 - 1.0, 0 means no modification.

    accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

device {
    name = alpsps/2-alps-dualpoint-touchpad 
    sensitivity = -0.3
}
